### ISSUE TITLE
don't run and compile by ubuntu 20.04 64bit

### ISSUE THREAD

**Issue by darcyg** [aul12/SerialToolbox#25]
hi,
 my program down for http://aul12.github.io/SerialToolbox/serialtoolbox.deb
 run it, output :
 

> $ SerialToolbox 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not find ui file

git clone sourcecode and cmake build

> $ cmake ..
> CMake Error at CMakeLists.txt:25 (find_package):
>   By not providing "FindQt5Quick.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5Quick",
>   but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Quick" with any
>   of the following names:
> 
>     Qt5QuickConfig.cmake
>     qt5quick-config.cmake
> 
>   Add the installation prefix of "Qt5Quick" to CMAKE_PREFIX_PATH or set
>   "Qt5Quick_DIR" to a directory containing one of the above files.  If
>   "Qt5Quick" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/works/temp/SerialToolbox/build/CMakeFiles/CMakeOutput.log".

i am run `sudo apt install qt5-default` but ...

thks

**Comment by sisco0** [comment]
Kindly use the following command line for installing qt5 dev dependencies:
`sudo apt install qttools5-dev qtbase5-dev qtdeclarative5-dev qml-module-qtquick-controls -y`
